default:
	chmod 777 Exp1/
	chmod 777 Exp2/
	chmod 777 Exp3/
	chmod 777 Exp1/exp1.py
	chmod 777 Exp1/exp1.tcl
	chmod 777 Exp2/exp2.py
	chmod 777 Exp2/exp2.tcl
	chmod 777 Exp3/exp3.py
	chmod 777 Exp3/exp3.tcl
