#!/bin/bash


# List of EC2 instances

ec2_instances=( "ec2-54-85-32-37.compute-1.amazonaws.com"
				"ec2-54-193-70-31.us-west-1.compute.amazonaws.com" 
				"ec2-52-38-67-246.us-west-2.compute.amazonaws.com" 
				"ec2-52-51-20-200.eu-west-1.compute.amazonaws.com" 
				"ec2-52-29-65-165.eu-central-1.compute.amazonaws.com"
				"ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com" 
				"ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com" 
				"ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com" 
				"ec2-54-233-185-94.sa-east-1.compute.amazonaws.com")


# Parsing command line arguments to find out port number, origin server name, cdn name, user name and key file 


while getopts "n:i:p:o:u:" opt; do         
    case $opt in
    p)
      portNum=$OPTARG
      ;;
    o)
      originServer=$OPTARG
      ;;
    n)
      cdnname=$OPTARG
      ;;
    u)
      userName=$OPTARG
      ;;
    i)
      keyFile=$OPTARG
      ;;
    esac
done

# Run HTTP server on each of the EC2 instances. 

for host in "${ec2_instances[@]}"; 
do 
	
	#echo "Running HTTP server " $host
	# Kill the processes currently running for the current username.
	ssh -i $keyFile $userName@$host 'nohup killall python > /dev/null 2>&1 &'

	# SSH into the EC2 instance using username and key file given, go into the server, and run the HTTP server instance
	ssh -i $keyFile $userName@$host "cd ~/httpserver/; nohup ./httpserver -p $portNum -o $originServer > /dev/null 2>&1 & "

	
done

#echo "HTTP server started "

# Initialize DNS server name to the assigned name

dnsserver=cs5700cdnproject.ccs.neu.edu

# SSH into the DNS server using the username and key file provided on command line. go into the DNS server folder and invoke the instance of DNS server.

ssh -i $keyFile $userName@$dnsserver "cd ~/dnsserver/; nohup ./dnsserver -p $portNum -n $cdnname > /dev/null 2>&1 & "


#echo "DNS Server started "



