#!/bin/bash


# List of EC2 instance names 

ec2_instances=( "ec2-54-85-32-37.compute-1.amazonaws.com"
				"ec2-54-193-70-31.us-west-1.compute.amazonaws.com" 
				"ec2-52-38-67-246.us-west-2.compute.amazonaws.com" 
				"ec2-52-51-20-200.eu-west-1.compute.amazonaws.com" 
				"ec2-52-29-65-165.eu-central-1.compute.amazonaws.com"
				"ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com" 
				"ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com" 
				"ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com" 
				"ec2-54-233-185-94.sa-east-1.compute.amazonaws.com")


# Parsing command line arguments to find out username and key file.



while getopts "n:i:p:o:u:" opt; do 
    case $opt in
    u)
      userName=$OPTARG
      ;;
    i)
      keyFile=$OPTARG
      ;;
    esac
done


# SSh into each of the EC2 instances and navigate to the HTTP server directory and kill all the 
# processes associated



for host in "${ec2_instances[@]}"; do 
	
	
	#echo "Stopping HTTP Server " $host
	ssh -i $keyFile $userName@$host "cd ~/httpserver/; killall python > /dev/null 2>&1 &"


done

# SSH into the DNS server and navigate to the DNS server location and kill all the 
# processes associated.

#echo "Stopping DNS Server" 

dnsserver=cs5700cdnproject.ccs.neu.edu
ssh -i $keyFile $userName@$dnsserver "cd ~/dnsserver/; killall python > /dev/null 2>&1 &"




